### ISSUE TITLE
Error at line 763 of /home/sites/development/hesteric/www/framework/core/Object.php

### ISSUE THREAD

**Issue by hesteric** [burnbright/silverstripe-omnipay#72]
I installed the Omnipay module by Composer. Now when I click Payments in the CMS menu this error appears:

Error at line 763 of /home/sites/development/hesteric/www/framework/core/Object.php

SilverStripe version: 3.1.6

**Comment by jedateach** [comment]
@hesteric have you resolved this issue?
I'm going to close this issue here, because I think it specific to your project, and not actually an omnipay issue. Feel free to continue getting assistance in the gitter chat: https://gitter.im/burnbright/silverstripe-omnipay
