### ISSUE TITLE
Payable Extension fails as it requires a has_one relationship from the Payment DataObject

### ISSUE THREAD

**Issue by fb3rasp** [burnbright/silverstripe-omnipay#76]
Hi,
When I apply the Payable Data Extension to a simple DataObject, like Order, I get a "[User Error] Uncaught Exception: No has_one found on class 'Payment', the has_many relation from 'Order' to 'Payment' requires a has_one on 'Payment'" error back and can not open the EditForm in the CMS of my Dependent Object anymore.

Not sure if you can do anything as it looks more like a core bug as $has_many relationships in DataExtensions may not work.

**Comment by jedateach** [comment]
@fb3rasp yes, I don't think there is currently a way to automatically specify the reverse has_one relationship on classes using the Payable extension. If you ever think of anything, let me know.

Thanks for pointing this issue out - I knew of it, but now I've documented it in the README.
