### ISSUE TITLE
Does this support DPS Payment Express and Recurring Payment

### ISSUE THREAD

**Issue by bbt-mahfuz** [burnbright/silverstripe-omnipay#81]
Hi,

I need to integrate a recurring payment system for Paid Members using DPS Payment Express gateway. Can I do that with this module? If yes, could you please give me some doc links to do so.

Thanks and regards,

Mahfuz

**Comment by jedateach** [comment]
No, the omnipay module does not yet support any recurring payments.

The omnipay library itself doesn't support recurring payments, other than what can be done with a tokenisation system. Some work has been started on this front: https://github.com/burnbright/silverstripe-omnipay/pull/63  However, I'm not sure if saved cards also still require interaction from the customer when making a purchase.
