### ISSUE TITLE
Authorize payment /delay capture

### ISSUE THREAD

**Issue by Sanderha** [burnbright/silverstripe-omnipay#86]
Is it possible to tell use the gateways Authorize function, instead of the purchase function? 
Silverstripe omnipay/code/services/AuthorizeCaptureService there are functions like authorize() and capture(), but these are empty, containing a "TODO". 

In Denmark it is a requirement to authorize payments first, and capture later. So to be able to use the gateways authorize function would be awesome.

Otherwise awesome module!

**Comment by jedateach** [comment]
This is a duplicate of #3
