### ISSUE TITLE
Make Payment Status translatable.

### ISSUE THREAD

**Issue by bummzack** [burnbright/silverstripe-omnipay#88]
I suggest adding an accessor method to `Payment`, something like `getLocalizedStatus` or `StatusNice` which returns a translation of the status instead of the raw enum-value.

**Comment by markguinn** [comment]
@bummzack have you checked the 1.2 branch? I think this might be fixed there.

**Comment by bummzack** [comment]
@markguinn it doesn't seem to be the case. The Gateway name is localized, but Payment status isn't. But since the payment status is being used in front- and backend in the shop-module, it might be worth localizing it too.

**Comment by markguinn** [comment]
I absolutely agree.

**Comment by bummzack** [comment]
Is it on purpose that this module doesn't have a `lang` folder? It makes use of the translation system, eg. `_t("Payment.MONEY", "Money")` but doesn't provide any language files. Instead some of these values are translated in the shop module.

I think language-files should cover the values for the specific module they belong to, right? Maybe we could add this to the 2.x milestone as well?

**Comment by markguinn** [comment]
I don't think it's on purpose, no. It's probably just not something Jeremy ever had to implement. I absolutely agree with you that it's appropriate for strings used in this module to be translated in this module. Shop isn't the only module that makes use of this one anyway. If you have time and interest in fixing this I'd certainly welcome a PR.

**Comment by bummzack** [comment]
Will do… I'll open another issue for it and get this one done first.
