### ISSUE TITLE
Payment filtering throws an error.

### ISSUE THREAD

**Issue by bummzack** [burnbright/silverstripe-omnipay#90]
Using master branch of silverstripe-omnipay and SilverStripe 3.2.1

    [Warning] trim() expects parameter 1 to be string, array given

The problem seems to be the `Created` field which gets scaffolded into a form field with `date` and `time` component. This in turn results in the following query-string: `[Created][date]=&q[Created][time]=` which can't be handled by ModelAdmin.

Not sure what the best fix would be… ideally this would be fixed in ModelAdmin?

**Comment by bummzack** [comment]
This is indeed a ModelAdmin issue and will most likely be fixed in the next SilverStripe release (since it was fixed with this PR: https://github.com/silverstripe/silverstripe-framework/pull/4619).

**Comment by markguinn** [comment]
I tend to disable the payment admin anyway as I don't think it's very useful. I hate having it just be broken though, especially not know how soon we might expect SS 3.2.2 to roll out.

**Comment by bummzack** [comment]
@markguinn We could fix it by overriding the method that errors in `PaymentAdmin`. Or even remove the `Created` field from the filter-fields altogether. I don't think it's that useful anyway, since it seems to only filter that given date. So you'd have to know the exact date and time you need a result for… a date-range would be much more useful here, but that would be a new feature altogether.

**Comment by markguinn** [comment]
I'm fine with removing Created entirely.

**Comment by bummzack** [comment]
@markguinn I just created a PR to remove `Created`. See: #92

**Comment by markguinn** [comment]
Merged.
